job_id: tree-pruner-baceaa54-30cf-4bdd-a253-a20897aa6496
email: scott.yanco@yale.edu
tree_base: mammaltree
tree_set: MamPhy_BDvr_Completed_5911sp_topoCons_NDexp
sample_size: 100
names: [Alces_alces, Canis_lupus, Cervus_elaphus, Odocoileus_hemionus, Odocoileus_virginianus,
  Puma_concolor, Ursus_americanus, Ursus_arctos]
sample_trees: [MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2272.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1230.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0889.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2691.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6806.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5841.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9864.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6327.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3089.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8798.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7100.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5706.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5003.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2300.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7368.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0752.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9718.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9638.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9827.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1911.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5502.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5681.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9341.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4032.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0605.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4251.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4961.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4003.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8039.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5937.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6030.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6651.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2830.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7969.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0759.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9116.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5909.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9736.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6245.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6446.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2375.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8462.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0373.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9748.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9021.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1792.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8526.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4419.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3579.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2293.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9688.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7236.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8198.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2710.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1881.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4797.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1305.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2712.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2762.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6824.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9454.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0133.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4458.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5781.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3046.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2637.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1010.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7021.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4956.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8771.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7483.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2366.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6258.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9903.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7613.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4903.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3583.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4694.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7362.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3867.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9418.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4948.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2339.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2314.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8527.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7970.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7041.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1721.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3638.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5327.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5383.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2635.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5276.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9236.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9648.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5338.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7719.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8042.tre,
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4876.tre, MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4642.tre]
status: COMPLETED
created_at: "2022-01-28T15:39:57Z"
completed_at: "2022-01-28T15:40:45Z"
bad_names: {MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0133.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0373.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0605.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0752.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0759.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_0889.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1010.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1230.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1305.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1721.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1792.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1881.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_1911.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2272.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2293.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2300.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2314.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2339.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2366.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2375.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2635.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2637.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2691.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2710.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2712.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2762.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_2830.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3046.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3089.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3579.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3583.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3638.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_3867.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4003.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4032.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4251.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4419.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4458.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4642.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4694.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4797.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4876.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4903.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4948.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4956.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_4961.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5003.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5276.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5327.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5338.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5383.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5502.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5681.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5706.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5781.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5841.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5909.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_5937.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6030.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6245.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6258.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6327.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6446.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6651.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6806.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_6824.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7021.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7041.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7100.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7236.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7362.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7368.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7483.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7613.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7719.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7969.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_7970.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8039.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8042.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8198.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8462.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8526.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8527.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8771.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_8798.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9021.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9116.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9236.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9341.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9418.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9454.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9638.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9648.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9688.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9718.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9736.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9748.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9827.tre: [],
  MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9864.tre: [], MamPhy_BDvr_Completed_5911sp_topoCons_NDexp_9903.tre: []}
