job_id: tree-pruner-05469463-d432-42ac-a726-58ff39a822b8
email: scott.yanco@yale.edu
tree_base: birdtree
tree_set: EricsonStage2Full
sample_size: 100
names: [Anser_albifrons, Chen_caerulescens, Chen_rossii, Anas_strepera, Anas_americana,
  Anas_platyrhynchos, Anas_discors, Anas_cyanoptera, Anas_clypeata, Anas_acuta, Anas_crecca,
  Coragyps_atratus, Cathartes_aura, Falco_peregrinus, Haliaeetus_leucocephalus, Circus_cyaneus,
  Buteo_lagopus, Aquila_chrysaetos, Grus_canadensis, Scolopax_minor, Numenius_americanus,
  Corvus_corax]
sample_trees: [EricsonStage2Full_4345.tre, EricsonStage2Full_6481.tre, EricsonStage2Full_4091.tre,
  EricsonStage2Full_9493.tre, EricsonStage2Full_4409.tre, EricsonStage2Full_0095.tre,
  EricsonStage2Full_2564.tre, EricsonStage2Full_8430.tre, EricsonStage2Full_0572.tre,
  EricsonStage2Full_3811.tre, EricsonStage2Full_2738.tre, EricsonStage2Full_9162.tre,
  EricsonStage2Full_9054.tre, EricsonStage2Full_5668.tre, EricsonStage2Full_5222.tre,
  EricsonStage2Full_5100.tre, EricsonStage2Full_9013.tre, EricsonStage2Full_8496.tre,
  EricsonStage2Full_8815.tre, EricsonStage2Full_4988.tre, EricsonStage2Full_8515.tre,
  EricsonStage2Full_9549.tre, EricsonStage2Full_8267.tre, EricsonStage2Full_9115.tre,
  EricsonStage2Full_4382.tre, EricsonStage2Full_8809.tre, EricsonStage2Full_8308.tre,
  EricsonStage2Full_8654.tre, EricsonStage2Full_6332.tre, EricsonStage2Full_0556.tre,
  EricsonStage2Full_3003.tre, EricsonStage2Full_9777.tre, EricsonStage2Full_8245.tre,
  EricsonStage2Full_8489.tre, EricsonStage2Full_1839.tre, EricsonStage2Full_0314.tre,
  EricsonStage2Full_2425.tre, EricsonStage2Full_6316.tre, EricsonStage2Full_9105.tre,
  EricsonStage2Full_8427.tre, EricsonStage2Full_9865.tre, EricsonStage2Full_8306.tre,
  EricsonStage2Full_7304.tre, EricsonStage2Full_2730.tre, EricsonStage2Full_0118.tre,
  EricsonStage2Full_7369.tre, EricsonStage2Full_6839.tre, EricsonStage2Full_8082.tre,
  EricsonStage2Full_6059.tre, EricsonStage2Full_1352.tre, EricsonStage2Full_8587.tre,
  EricsonStage2Full_6990.tre, EricsonStage2Full_9419.tre, EricsonStage2Full_4115.tre,
  EricsonStage2Full_8838.tre, EricsonStage2Full_7651.tre, EricsonStage2Full_8236.tre,
  EricsonStage2Full_3890.tre, EricsonStage2Full_4110.tre, EricsonStage2Full_8979.tre,
  EricsonStage2Full_8198.tre, EricsonStage2Full_0924.tre, EricsonStage2Full_8710.tre,
  EricsonStage2Full_0747.tre, EricsonStage2Full_9716.tre, EricsonStage2Full_0331.tre,
  EricsonStage2Full_9959.tre, EricsonStage2Full_1827.tre, EricsonStage2Full_6186.tre,
  EricsonStage2Full_7122.tre, EricsonStage2Full_4519.tre, EricsonStage2Full_4676.tre,
  EricsonStage2Full_5052.tre, EricsonStage2Full_0591.tre, EricsonStage2Full_7071.tre,
  EricsonStage2Full_2545.tre, EricsonStage2Full_0949.tre, EricsonStage2Full_8971.tre,
  EricsonStage2Full_9409.tre, EricsonStage2Full_4655.tre, EricsonStage2Full_6147.tre,
  EricsonStage2Full_8305.tre, EricsonStage2Full_2063.tre, EricsonStage2Full_2886.tre,
  EricsonStage2Full_9050.tre, EricsonStage2Full_5209.tre, EricsonStage2Full_5546.tre,
  EricsonStage2Full_0441.tre, EricsonStage2Full_9867.tre, EricsonStage2Full_9272.tre,
  EricsonStage2Full_0734.tre, EricsonStage2Full_8626.tre, EricsonStage2Full_4433.tre,
  EricsonStage2Full_7733.tre, EricsonStage2Full_4832.tre, EricsonStage2Full_8195.tre,
  EricsonStage2Full_6002.tre, EricsonStage2Full_0202.tre, EricsonStage2Full_9206.tre,
  EricsonStage2Full_6554.tre]
status: COMPLETED
created_at: "2022-01-28T15:39:02Z"
completed_at: "2022-01-28T15:39:51Z"
bad_names: {EricsonStage2Full_0095.tre: [], EricsonStage2Full_0118.tre: [], EricsonStage2Full_0202.tre: [],
  EricsonStage2Full_0314.tre: [], EricsonStage2Full_0331.tre: [], EricsonStage2Full_0441.tre: [],
  EricsonStage2Full_0556.tre: [], EricsonStage2Full_0572.tre: [], EricsonStage2Full_0591.tre: [],
  EricsonStage2Full_0734.tre: [], EricsonStage2Full_0747.tre: [], EricsonStage2Full_0924.tre: [],
  EricsonStage2Full_0949.tre: [], EricsonStage2Full_1352.tre: [], EricsonStage2Full_1827.tre: [],
  EricsonStage2Full_1839.tre: [], EricsonStage2Full_2063.tre: [], EricsonStage2Full_2425.tre: [],
  EricsonStage2Full_2545.tre: [], EricsonStage2Full_2564.tre: [], EricsonStage2Full_2730.tre: [],
  EricsonStage2Full_2738.tre: [], EricsonStage2Full_2886.tre: [], EricsonStage2Full_3003.tre: [],
  EricsonStage2Full_3811.tre: [], EricsonStage2Full_3890.tre: [], EricsonStage2Full_4091.tre: [],
  EricsonStage2Full_4110.tre: [], EricsonStage2Full_4115.tre: [], EricsonStage2Full_4345.tre: [],
  EricsonStage2Full_4382.tre: [], EricsonStage2Full_4409.tre: [], EricsonStage2Full_4433.tre: [],
  EricsonStage2Full_4519.tre: [], EricsonStage2Full_4655.tre: [], EricsonStage2Full_4676.tre: [],
  EricsonStage2Full_4832.tre: [], EricsonStage2Full_4988.tre: [], EricsonStage2Full_5052.tre: [],
  EricsonStage2Full_5100.tre: [], EricsonStage2Full_5209.tre: [], EricsonStage2Full_5222.tre: [],
  EricsonStage2Full_5546.tre: [], EricsonStage2Full_5668.tre: [], EricsonStage2Full_6002.tre: [],
  EricsonStage2Full_6059.tre: [], EricsonStage2Full_6147.tre: [], EricsonStage2Full_6186.tre: [],
  EricsonStage2Full_6316.tre: [], EricsonStage2Full_6332.tre: [], EricsonStage2Full_6481.tre: [],
  EricsonStage2Full_6554.tre: [], EricsonStage2Full_6839.tre: [], EricsonStage2Full_6990.tre: [],
  EricsonStage2Full_7071.tre: [], EricsonStage2Full_7122.tre: [], EricsonStage2Full_7304.tre: [],
  EricsonStage2Full_7369.tre: [], EricsonStage2Full_7651.tre: [], EricsonStage2Full_7733.tre: [],
  EricsonStage2Full_8082.tre: [], EricsonStage2Full_8195.tre: [], EricsonStage2Full_8198.tre: [],
  EricsonStage2Full_8236.tre: [], EricsonStage2Full_8245.tre: [], EricsonStage2Full_8267.tre: [],
  EricsonStage2Full_8305.tre: [], EricsonStage2Full_8306.tre: [], EricsonStage2Full_8308.tre: [],
  EricsonStage2Full_8427.tre: [], EricsonStage2Full_8430.tre: [], EricsonStage2Full_8489.tre: [],
  EricsonStage2Full_8496.tre: [], EricsonStage2Full_8515.tre: [], EricsonStage2Full_8587.tre: [],
  EricsonStage2Full_8626.tre: [], EricsonStage2Full_8654.tre: [], EricsonStage2Full_8710.tre: [],
  EricsonStage2Full_8809.tre: [], EricsonStage2Full_8815.tre: [], EricsonStage2Full_8838.tre: [],
  EricsonStage2Full_8971.tre: [], EricsonStage2Full_8979.tre: [], EricsonStage2Full_9013.tre: [],
  EricsonStage2Full_9050.tre: [], EricsonStage2Full_9054.tre: [], EricsonStage2Full_9105.tre: [],
  EricsonStage2Full_9115.tre: [], EricsonStage2Full_9162.tre: [], EricsonStage2Full_9206.tre: [],
  EricsonStage2Full_9272.tre: [], EricsonStage2Full_9409.tre: [], EricsonStage2Full_9419.tre: [],
  EricsonStage2Full_9493.tre: [], EricsonStage2Full_9549.tre: [], EricsonStage2Full_9716.tre: [],
  EricsonStage2Full_9777.tre: [], EricsonStage2Full_9865.tre: [], EricsonStage2Full_9867.tre: [],
  EricsonStage2Full_9959.tre: []}
